[versions]
kotlin = "2.2.21"
agp = "8.13.1"
grgit = "5.3.3"
annotation = "1.9.1"
browser = "1.9.0"
okio = "3.16.4"
coreKtx = "1.17.0"
coroutines = "1.10.2"
serializationJson = "1.9.0"
compose-bom = "2025.11.01"
activity-compose = "1.12.0"
lifecycle = "2.10.0"
coil = "2.7.0"
desugar = "2.1.5"
dokka = "1.9.20"

#Tests
junit = "4.13.2"
hamcrest = "3.0"
mockitoCore = "5.20.0"
mockitoKotlin = "6.1.0"

robolectric = "4.16"
assertjCore = "3.27.6"
junitExt = "1.3.0"
truthExt = "1.7.0"
truth = "1.4.5"
testParameterInjector = "1.20"
xmlpull = "1.1.3.1"

[libraries]
browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }
androidGradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlinGradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
dokkaPlugin = { group = "org.jetbrains.dokka", name = "dokka-gradle-plugin", version.ref = "dokka" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
serializationJson = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serializationJson" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
desugar-jdk-libs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar" }

#Tests
#noinspection UnusedVersionCatalogEntry
junit = { group = "junit", name = "junit", version.ref = "junit" }
#noinspection UnusedVersionCatalogEntry
hamcrest = { group = "org.hamcrest", name = "hamcrest", version.ref = "hamcrest" }
#noinspection UnusedVersionCatalogEntry
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockitoCore" }
#noinspection UnusedVersionCatalogEntry
mockitoKotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockitoKotlin" }
#noinspection UnusedVersionCatalogEntry
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
#noinspection UnusedVersionCatalogEntry
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertjCore" }
#noinspection UnusedVersionCatalogEntry
junitExt = { group = "androidx.test.ext", name = "junit", version.ref = "junitExt" }
#noinspection UnusedVersionCatalogEntry
truthExt = { group = "androidx.test.ext", name = "truth", version.ref = "truthExt" }
#noinspection UnusedVersionCatalogEntry
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
#noinspection UnusedVersionCatalogEntry
testParameterInjector = { group = "com.google.testparameterinjector", name = "test-parameter-injector", version.ref = "testParameterInjector" }
#noinspection UnusedVersionCatalogEntry
xmlpull = { group = "xmlpull", name = "xmlpull", version.ref = "xmlpull" }
#noinspection UnusedVersionCatalogEntry
coroutinesTest = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }

[plugins]
agp-application = { id = "com.android.application" }
agp-library = { id = "com.android.library" }
grgit = { id = "org.ajoberstar.grgit", version.ref = "grgit" }
kotlin-android = { id = "org.jetbrains.kotlin.android" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka" }